
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DPP.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Comment
{

    public int CommentID { get; set; }

    public Nullable<int> UserID { get; set; }

    public Nullable<int> PlaceID { get; set; }

    public Nullable<int> EventID { get; set; }

    public Nullable<int> GroupID { get; set; }

    public Nullable<int> PictureID { get; set; }

    public Nullable<int> VideoID { get; set; }

    public Nullable<int> StyleID { get; set; }

    public string Comment1 { get; set; }

    public System.DateTime CommentDateTime { get; set; }



    public virtual Event Event { get; set; }

    public virtual Group Group { get; set; }

    public virtual Picture Picture { get; set; }

    public virtual Place Place { get; set; }

    public virtual Style Style { get; set; }

    public virtual User User { get; set; }

    public virtual Video Video { get; set; }

}

}
