//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPP.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DanceDBEntities : DbContext
    {
        public DanceDBEntities()
            : base("name=DanceDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<EventMember> EventMembers { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<EventStyle> EventStyles { get; set; }
        public virtual DbSet<GroupEvent> GroupEvents { get; set; }
        public virtual DbSet<GroupMember> GroupMembers { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<GroupStyle> GroupStyles { get; set; }
        public virtual DbSet<Picture> Pictures { get; set; }
        public virtual DbSet<Place> Places { get; set; }
        public virtual DbSet<Review> Reviews { get; set; }
        public virtual DbSet<Style> Styles { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Video> Videos { get; set; }
        public virtual DbSet<GroupRehearsal> GroupRehearsals { get; set; }
        public virtual DbSet<Dancer> Dancers { get; set; }
        public virtual DbSet<Owner> Owners { get; set; }
        public virtual DbSet<Promoter> Promoters { get; set; }
        public virtual DbSet<Teacher> Teachers { get; set; }
        public virtual DbSet<Friendship> Friendships { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
    
        public virtual ObjectResult<usp_Users_Search_Result> usp_Users_Search(Nullable<int> userID, string facebookLink, string urlName)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            var facebookLinkParameter = facebookLink != null ?
                new ObjectParameter("FacebookLink", facebookLink) :
                new ObjectParameter("FacebookLink", typeof(string));
    
            var urlNameParameter = urlName != null ?
                new ObjectParameter("UrlName", urlName) :
                new ObjectParameter("UrlName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_Users_Search_Result>("usp_Users_Search", userIDParameter, facebookLinkParameter, urlNameParameter);
        }
    
        public virtual int usp_Users_Update(ObjectParameter userID, string firstName, string lastName, string facebookLink, string urlName)
        {
            var firstNameParameter = firstName != null ?
                new ObjectParameter("FirstName", firstName) :
                new ObjectParameter("FirstName", typeof(string));
    
            var lastNameParameter = lastName != null ?
                new ObjectParameter("LastName", lastName) :
                new ObjectParameter("LastName", typeof(string));
    
            var facebookLinkParameter = facebookLink != null ?
                new ObjectParameter("FacebookLink", facebookLink) :
                new ObjectParameter("FacebookLink", typeof(string));
    
            var urlNameParameter = urlName != null ?
                new ObjectParameter("UrlName", urlName) :
                new ObjectParameter("UrlName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_Users_Update", userID, firstNameParameter, lastNameParameter, facebookLinkParameter, urlNameParameter);
        }
    }
}
