//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPP.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DanceDBEntities : DbContext
    {
        public DanceDBEntities()
            : base("name=DanceDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<EventMember> EventMembers { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<EventStyle> EventStyles { get; set; }
        public virtual DbSet<GroupEvent> GroupEvents { get; set; }
        public virtual DbSet<GroupMember> GroupMembers { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<GroupStyle> GroupStyles { get; set; }
        public virtual DbSet<Picture> Pictures { get; set; }
        public virtual DbSet<Place> Places { get; set; }
        public virtual DbSet<Review> Reviews { get; set; }
        public virtual DbSet<Style> Styles { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Video> Videos { get; set; }
        public virtual DbSet<GroupRehearsal> GroupRehearsals { get; set; }
        public virtual DbSet<Dancer> Dancers { get; set; }
        public virtual DbSet<Owner> Owners { get; set; }
        public virtual DbSet<Promoter> Promoters { get; set; }
        public virtual DbSet<Teacher> Teachers { get; set; }
        public virtual DbSet<Friendship> Friendships { get; set; }
    }
}
