//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public abstract partial class Event
    {
        public Event()
        {
            this.Comments = new HashSet<Comment>();
            this.EventMembers = new HashSet<EventMember>();
            this.Events1 = new HashSet<Event>();
            this.EventStyles = new HashSet<EventStyle>();
            this.GroupEvents = new HashSet<GroupEvent>();
            this.Pictures = new HashSet<Picture>();
            this.Reviews = new HashSet<Review>();
            this.Videos = new HashSet<Video>();
        }
    
        public int EventID { get; set; }
        public string EventName { get; set; }
        public string Description { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<System.TimeSpan> EndTime { get; set; }
        public bool AllDay { get; set; }
        public string Link { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public string LocationType { get; set; }
        public string Address { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Country { get; set; }
        public Nullable<int> ParentEventID { get; set; }
        public Nullable<int> Frequency { get; set; }
        public string DaysOfWeek { get; set; }
        public Nullable<int> GroupID { get; set; }
    
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<EventMember> EventMembers { get; set; }
        public virtual ICollection<Event> Events1 { get; set; }
        public virtual Event Event1 { get; set; }
        public virtual ICollection<EventStyle> EventStyles { get; set; }
        public virtual ICollection<GroupEvent> GroupEvents { get; set; }
        public virtual ICollection<Picture> Pictures { get; set; }
        public virtual ICollection<Review> Reviews { get; set; }
        public virtual ICollection<Video> Videos { get; set; }
        public virtual Group Group { get; set; }
    }
}
