
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DPP.Models
{

using System;
    using System.Collections.Generic;
    
public partial class EventStyle
{

    public int EventStyleID { get; set; }

    public int EventID { get; set; }

    public int StyleID { get; set; }



    public virtual Event Event { get; set; }

    public virtual Style Style { get; set; }

}

}
