//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Friendship
    {
        public int FriendshipID { get; set; }
        public int UserID { get; set; }
        public int FriendUserID { get; set; }
        public Nullable<int> FriendStatus { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
