
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DPP.Models
{

using System;
    using System.Collections.Generic;
    
public partial class GroupMember
{

    public int GroupMemberID { get; set; }

    public int GroupID { get; set; }

    public int UserID { get; set; }

    public System.DateTime JoinDate { get; set; }

    public bool Admin { get; set; }



    public virtual Group Group { get; set; }

    public virtual User User { get; set; }

}

}
