//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Promoter
    {
        public int UserID { get; set; }
        public string ContactEmail { get; set; }
        public string Website { get; set; }
        public string FacebookPage { get; set; }
        public string UrlName { get; set; }
    
        public virtual User User { get; set; }
    }
}
