//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPP.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Review
    {
        public int ReviewID { get; set; }
        public int AuthorUserID { get; set; }
        public string Review1 { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public System.DateTime ReviewDate { get; set; }
        public double Stars { get; set; }
        public Nullable<int> EventID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> PlaceID { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual Place Place { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
