//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Team
    {
        public Team()
        {
            this.Comments = new HashSet<Comment>();
            this.Pictures = new HashSet<Picture>();
            this.Rehearsals = new HashSet<Rehearsal>();
            this.TeamEvents = new HashSet<TeamEvent>();
            this.TeamMembers = new HashSet<TeamMember>();
            this.Teams1 = new HashSet<Team>();
            this.Videos = new HashSet<Video>();
        }
    
        public int TeamID { get; set; }
        public string TeamName { get; set; }
        public string Style { get; set; }
        public string SkillLevel { get; set; }
        public bool Open { get; set; }
        public bool Public { get; set; }
        public Nullable<int> ParentTeamID { get; set; }
    
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<Picture> Pictures { get; set; }
        public virtual ICollection<Rehearsal> Rehearsals { get; set; }
        public virtual ICollection<TeamEvent> TeamEvents { get; set; }
        public virtual ICollection<TeamMember> TeamMembers { get; set; }
        public virtual ICollection<Team> Teams1 { get; set; }
        public virtual Team Team1 { get; set; }
        public virtual ICollection<Video> Videos { get; set; }
    }
}
