//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Comments = new HashSet<Comment>();
            this.EventMembers = new HashSet<EventMember>();
            this.GroupMembers = new HashSet<GroupMember>();
            this.Pictures = new HashSet<Picture>();
            this.Pictures1 = new HashSet<Picture>();
            this.Reviews = new HashSet<Review>();
            this.Reviews1 = new HashSet<Review>();
            this.Videos = new HashSet<Video>();
            this.Friendships = new HashSet<Friendship>();
            this.Friendships1 = new HashSet<Friendship>();
        }
    
        public int UserID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public System.DateTime JoinDate { get; set; }
        public string FacebookLink { get; set; }
        public string UrlName { get; set; }
    
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<EventMember> EventMembers { get; set; }
        public virtual ICollection<GroupMember> GroupMembers { get; set; }
        public virtual ICollection<Picture> Pictures { get; set; }
        public virtual ICollection<Picture> Pictures1 { get; set; }
        public virtual ICollection<Review> Reviews { get; set; }
        public virtual ICollection<Review> Reviews1 { get; set; }
        public virtual ICollection<Video> Videos { get; set; }
        public virtual Dancer Dancer { get; set; }
        public virtual Owner Owner { get; set; }
        public virtual Promoter Promoter { get; set; }
        public virtual Teacher Teacher { get; set; }
        public virtual ICollection<Friendship> Friendships { get; set; }
        public virtual ICollection<Friendship> Friendships1 { get; set; }
    }
}
